package democurrency;


import javax.swing.JOptionPane;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Currenframe extends javax.swing.JFrame {
    Double djual,dbeli;
    
        public static String ambilData(String THISurl)
    {
        String jsondata = "";
        try {
            URL url = new URL(THISurl);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();    //buka koneksi URL
            connection.setRequestMethod("GET");                                         //untuk direct access URL tersebut
            connection.connect();                                                       //untuk connect, duh...
            Scanner urldata = new Scanner(url.openStream());        
            while(urldata.hasNext())
            {
                    jsondata += urldata.nextLine();
            }
            urldata.close();
        }
        catch (Exception e) {       //catch untuk ngambil semua code error pada fungsi, Exception e untuk semua error yang terjadi ditampung pada variabel "e" untuk dapat di print
           e.printStackTrace();     //print error
        }
        return jsondata;
    }
    
    public void usd (String data){
        data = ambilData("http://www.adisurya.net/kurs-bca/get?MataUang=USD");
        String jual = data.substring(75,80);
        String beli = data.substring(90,95);
        djual = Double.parseDouble(jual);
        dbeli = Double.parseDouble(beli);
    }
    public void cnh (String data){
        data = ambilData("http://www.adisurya.net/kurs-bca/get?MataUang=cnh");
        String jual = data.substring(75,81);
        String beli = data.substring(92,98);
        djual = Double.parseDouble(jual);
        dbeli = Double.parseDouble(beli);
    }
    public void eur (String data){
        data = ambilData("http://www.adisurya.net/kurs-bca/get?MataUang=eur");
        String jual = data.substring(75,82);
        String beli = data.substring(93,100);
        djual = Double.parseDouble(jual);
        dbeli = Double.parseDouble(beli);
    }
    public void dkk (String data){
        data = ambilData("http://www.adisurya.net/kurs-bca/get?MataUang=dkk");
        String jual = data.substring(75,81);
        String beli = data.substring(92,98);
        djual = Double.parseDouble(jual);
        dbeli = Double.parseDouble(beli);
    }
    public void gbp (String data){
        data = ambilData("http://www.adisurya.net/kurs-bca/get?MataUang=gbp");
        String jual = data.substring(75,82);
        String beli = data.substring(93,100);
        djual = Double.parseDouble(jual);
        dbeli = Double.parseDouble(beli);
    }
    public void jpy (String data){
        data = ambilData("http://www.adisurya.net/kurs-bca/get?MataUang=jpy");
        String jual = data.substring(75,80);
        String beli = data.substring(91,96);
        djual = Double.parseDouble(jual);
        dbeli = Double.parseDouble(beli);
    }
    public void sgd (String data){
        data = ambilData("http://www.adisurya.net/kurs-bca/get?MataUang=sgd");
        String jual = data.substring(75,82);
        String beli = data.substring(93,100);
        djual = Double.parseDouble(jual);
        dbeli = Double.parseDouble(beli);
    }
    public void aud (String data){
        data = ambilData("http://www.adisurya.net/kurs-bca/get?MataUang=aud");
        String jual = data.substring(75,81);
        String beli = data.substring(92,98);
        djual = Double.parseDouble(jual);
        dbeli = Double.parseDouble(beli);
    }
    
    /**
     * Creates new form Currenframe
     */
    public Currenframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        choose = new javax.swing.JComboBox<>();
        nominal = new javax.swing.JTextField();
        Convert = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        hasil = new javax.swing.JLabel();
        tujuan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Uciputra\\Tugas\\AP\\Ezsan currency\\ae74548dc83afc7821034ac0567b9e38.jpg")); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\Uciputra\\Tugas\\AP\\Ezsan currency\\ae74548dc83afc7821034ac0567b9e38.jpg")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\Uciputra\\Tugas\\AP\\Ezsan currency\\1x\\3Asset 2.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EZSAN RUPIAH CURRENCY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 140, 520, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONVERTER");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 170, 270, 43);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(537, 443, 0, 0);

        choose.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        choose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One", "Rupiah to Other", "Other to Rupiah" }));
        choose.setBorder(null);
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        jPanel1.add(choose);
        choose.setBounds(130, 220, 191, 51);

        nominal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        nominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominalActionPerformed(evt);
            }
        });
        jPanel1.add(nominal);
        nominal.setBounds(130, 280, 333, 51);

        Convert.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Convert.setText("Convert");
        Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertActionPerformed(evt);
            }
        });
        jPanel1.add(Convert);
        Convert.setBounds(130, 410, 159, 51);

        Reset.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel1.add(Reset);
        Reset.setBounds(300, 410, 159, 51);

        Cancel.setBackground(new java.awt.Color(255, 51, 51));
        Cancel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel);
        Cancel.setBounds(130, 470, 333, 51);

        hasil.setBackground(new java.awt.Color(255, 255, 255));
        hasil.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        hasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(hasil);
        hasil.setBounds(130, 340, 333, 51);

        tujuan.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        tujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "USD", "CNH", "EUR", "DKK", "GBP", "JPY", "SGD", "AUD" }));
        tujuan.setBorder(null);
        tujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuanActionPerformed(evt);
            }
        });
        jPanel1.add(tujuan);
        tujuan.setBounds(330, 220, 133, 51);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Keterangan : \nUSD = United States Dollar\t\tGBP = Pound sterling\nCNH = Chinese Yuan\t\tJPY = Japanese Yen\nEUR = Euro\t\t\tSGD = Singapore Dollar\nDKK = Danish Krone\t\tAUD = Australian Dollar\n");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 530, 450, 100);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(15, 14, 0, 0);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(130, 340, 330, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/democurrency/3Asset 7.png"))); // NOI18N
        jLabel7.setText("dklaskdl");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(-110, -10, 760, 1190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tujuanActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CancelActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        choose.setSelectedIndex(0);
        tujuan.setSelectedIndex(0);
        nominal.setText(null);
        hasil.setText(null);
    }//GEN-LAST:event_ResetActionPerformed

    private void ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertActionPerformed
        // TODO add your handling code here:
        Currenframe c = new Currenframe();
        String data="";
        if(nominal.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Masukkan Input Jumlah Nominal Uang yang Akan Dikonversi");
        }
//        if(!nominal.getText().contains("1")||!nominal.getText().contains("2")||!nominal.getText().contains("3")||!nominal.getText().contains("4")||!nominal.getText().contains("5")||!nominal.getText().contains("6")||!nominal.getText().contains("7")||!nominal.getText().contains("8")||!nominal.getText().contains("9")||!nominal.getText().contains("0")||!nominal.getText().contains(".")||!nominal.getText().contains(",")){
//            JOptionPane.showMessageDialog(this,"Input Angka Woiii1!1!1!");
//        }
        else{
        double input = Double.parseDouble(nominal.getText());

        if (choose.getSelectedItem().equals("Rupiah to Other")) {
            if(tujuan.getSelectedItem().equals("USD")){
                c.usd(data);
                String convert = String.format("$ %.2f", input/c.djual);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("CNH")){
                c.cnh(data);
                String convert = String.format("¥ %.2f", input/c.djual);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("EUR")){
                c.eur(data);
                String convert = String.format("€ %.2f", input/c.djual);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("DKK")){
                c.dkk(data);
                String convert = String.format("kr %.2f", input/c.djual);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("GBP")){
                c.gbp(data);
                String convert = String.format("£ %.2f", input/c.djual);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("JPY")){
                c.jpy(data);
                String convert = String.format("¥ %.2f", input/c.djual);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("SGD")){
                c.sgd(data);
                String convert = String.format("$ %.2f", input/c.djual);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("AUD")){
                c.aud(data);
                String convert = String.format("$ %.2f", input/c.djual);
                hasil.setText(convert);
            }
        }else if (choose.getSelectedItem().equals("Other to Rupiah")) {
            if(tujuan.getSelectedItem().equals("USD")){
                c.usd(data);
                String convert = String.format("Rp %.2f", input*c.dbeli);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("CNH")){
                c.cnh(data);
                String convert = String.format("Rp %.2f", input*c.dbeli);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("EUR")){
                c.eur(data);
                String convert = String.format("Rp %.2f", input*c.dbeli);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("DKK")){
                c.dkk(data);
                String convert = String.format("Rp %.2f", input*c.dbeli);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("GBP")){
                c.gbp(data);
                String convert = String.format("Rp %.2f", input*c.dbeli);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("JPY")){
                c.jpy(data);
                String convert = String.format("Rp %.2f", input*c.dbeli);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("SGD")){
                c.sgd(data);
                String convert = String.format("Rp %.2f", input*c.dbeli);
                hasil.setText(convert);
            }else if(tujuan.getSelectedItem().equals("AUD")){
                c.aud(data);
                String convert = String.format("Rp %.2f", input*c.dbeli);
                hasil.setText(convert);
            }
        }
        }

        if (choose.getSelectedItem().toString().equalsIgnoreCase("Choose One")) {
            JOptionPane.showMessageDialog(this,"Pilih Salah Satu");
        }if (tujuan.getSelectedItem().toString().equalsIgnoreCase("Choose")) {
            JOptionPane.showMessageDialog(this,"Pilih Tujuan Konversi");
        }
    }//GEN-LAST:event_ConvertActionPerformed

    private void nominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nominalActionPerformed

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Currenframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Currenframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Currenframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Currenframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Currenframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Convert;
    private javax.swing.JButton Reset;
    private javax.swing.JComboBox<String> choose;
    private javax.swing.JLabel hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nominal;
    private javax.swing.JComboBox<String> tujuan;
    // End of variables declaration//GEN-END:variables
}
